#  ____   _                    _
# |  _ \ (_)                  | |
# | |_) | _  ___   ___  _   _ | |_  ___
# |  _ < | |/ __| / __|| | | || __|/ _ \
# | |_) || |\__ \| (__ | |_| || |_|  __/
# |____/ |_||___/ \___| \__,_| \__|\___|
# =======================================

# === TOKEN === #
# Set your token here
# If you wish to fetch the Bot's Token from your environmental varaibles (RECOMMENDED), set token to "env"
token = "env"

[database]
type = "sqlite"  # SQLite / PostgreSQL

  [database.sqlite]
  filename  = "servers.db"

  # === POSTGRESQL ===
  # Only modify this section if you plan on using a dedicated DB
  [database.postgresql]
  user      = "bot"
  password  = ""
  database  = ""
  host      =  "localhost"

